services:
  backend:
    build:
      context: backend
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./data/:/app/data/
    environment:
      - DATA_DIR=/app/data
      - MONGODB_URI=mongodb://mongodb/insta-insights
      - INSTAGRAM_API_KEY=${INSTAGRAM_API_KEY}
    depends_on:
      - mongodb

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run start
    depends_on:
      - backend
