// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ReadRootGetData, ReadRootGetResponse } from './types.gen';

/**
 * Read Root
 * @param data The data for the request.
 * @param data.testing
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const readRootGet = (data: ReadRootGetData = {}): CancelablePromise<ReadRootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/',
    query: {
        testing: data.testing
    },
    errors: {
        422: 'Validation Error'
    }
}); };