// This file is auto-generated by @hey-api/openapi-ts

export type Account = {
    username: string;
    full_name: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Report = {
    username: string;
    date: string;
    followers: Array<Account>;
    following: Array<Account>;
    dont_follow_me_back: Array<Account>;
    i_dont_follow_back: Array<Account>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ReadRootGetData = {
    testing?: boolean;
};

export type ReadRootGetResponse = (unknown);

export type CreateReportReportsPostData = {
    requestBody: Report;
    testing?: boolean;
};

export type CreateReportReportsPostResponse = (Report);

export type ReadReportsReportsGetData = {
    testing?: boolean;
};

export type ReadReportsReportsGetResponse = (Array<Report>);

export type ReadReportReportsUsernameGetData = {
    testing?: boolean;
    username: string;
};

export type ReadReportReportsUsernameGetResponse = (Report);

export type UpdateReportReportsUsernamePutData = {
    requestBody: Report;
    testing?: boolean;
    username: string;
};

export type UpdateReportReportsUsernamePutResponse = (Report);

export type DeleteReportReportsUsernameDeleteData = {
    testing?: boolean;
    username: string;
};

export type DeleteReportReportsUsernameDeleteResponse = (Report);